### ISSUE TITLE
Interview scheduling sometimes yields 500

### ISSUE THREAD

**Issue by hathix** [nickboucher/nova#19]
On `http://nova.ga/schedule`, I tried scheduling interviews but I got a 500 error. I realized it was because my browser doesn't support the HTML5 `date` and `time` field types, and as such I couldn't enter information in the proper format. (e.g. I put in `7:00` instead of the required `07:00 PM`.) But once I opened Chrome, which supports these fields, it worked perfectly.

So I'd suggest adding validation client and/or server side to ensure that inputs are well-formatted.

**Comment by nickboucher** [comment]
Indeed, that is the problem. Error log for investigation purposes:

```
[Tue Feb 21 14:00:51.730743 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640] [2017-02-21 14:00:51,730] ERROR in app: Exception on /schedule [POST]
[Tue Feb 21 14:00:51.730751 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640] Traceback (most recent call last):
[Tue Feb 21 14:00:51.730754 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
[Tue Feb 21 14:00:51.730756 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     response = self.full_dispatch_request()
[Tue Feb 21 14:00:51.730758 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Tue Feb 21 14:00:51.730760 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     rv = self.handle_user_exception(e)
[Tue Feb 21 14:00:51.730762 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Tue Feb 21 14:00:51.730764 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     reraise(exc_type, exc_value, tb)
[Tue Feb 21 14:00:51.730766 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
[Tue Feb 21 14:00:51.730777 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     raise value
[Tue Feb 21 14:00:51.730779 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Tue Feb 21 14:00:51.730781 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     rv = self.dispatch_request()
[Tue Feb 21 14:00:51.730783 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
[Tue Feb 21 14:00:51.730784 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Feb 21 14:00:51.730786 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/local/lib/python3.5/dist-packages/flask_login/utils.py", line 228, in decorated_view
[Tue Feb 21 14:00:51.730788 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     return func(*args, **kwargs)
[Tue Feb 21 14:00:51.730790 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/home/nova/nova-app/helpers.py", line 155, in decorated_view
[Tue Feb 21 14:00:51.730792 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     return func(*args, **kwargs)
[Tue Feb 21 14:00:51.730793 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/home/nova/nova-app/application.py", line 1676, in schedule_interviews
[Tue Feb 21 14:00:51.730795 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     date = eastern.localize(datetime.strptime(date_str, '%Y-%m-%d'))
[Tue Feb 21 14:00:51.730797 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
[Tue Feb 21 14:00:51.730799 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     tt, fraction = _strptime(data_string, format)
[Tue Feb 21 14:00:51.730801 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]   File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
[Tue Feb 21 14:00:51.730802 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]     (data_string, format))
[Tue Feb 21 14:00:51.730805 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640] ValueError: time data '02/22/2017' does not match format '%Y-%m-%d'
[Tue Feb 21 14:00:51.730816 2017] [wsgi:error] [pid 18812:tid 139737855649536] [remote 65.112.8.200:45640]
[Tue Feb 21 14:03:51.278867 2017] [wsgi:error] [pid 18812:tid 139737855649536] 2017-02-22
```
